version: 2.1

# for easier referencing in the rest of the config
references:
  js_deps_cache_key: &js_deps_cache_key
    v1-dependencies-{{ checksum "package-lock.json" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key
    v1-dependencies-
  # workspace saves files across different `jobs` in a single `workflow`
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  setup_fs:
    description: "Attaches workspace, checks out code and restores node_modules"
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run:
          name: Restore built helix site
          command: |
            set -exu
            mkdir -p /tmp/workspace/.hlx
            mkdir -p .hlx
            [ -d /tmp/workspace/.hlx/build ] && mv -f /tmp/workspace/.hlx/build .hlx/. || true
            [ -f /tmp/workspace/.hlx/helix-config.yaml ] && mv -f /tmp/workspace/helix-config.yaml . || true

orbs:
  sauce-connect: saucelabs/sauce-connect@volatile
executors:
  helix:
    docker:
      - image: circleci/node:8-jessie-browsers
jobs:
  install:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  build:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: Build helix
          command: npm run build
      - run:
          name: Persist built helix site
          command: |
            set -exu
            mkdir -p /tmp/workspace/.hlx
            mv .hlx/* /tmp/workspace/.hlx/.
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .hlx

  lint:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: Lint via eslint
          command: npm run lint

  unit_tests:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: Run unit tests
          command: npm run test:unit

  end_to_end_tests:
    executor: helix
    steps:
      - setup_fs
      # Open up the Sauce Labs tunnel
      - sauce-connect/install:
          version: 4.5.3
      - sauce-connect/open_tunnel:
          # NOTE: the env vars are hardcoded as SAUCELABS_USER and
          # SAUCELABS_KEY
          tunnel_identifier: ${SAUCELABS_USER}
      - run:
          name: Run end to end tests
          command: npm run test:e2e-helix-sauce -- --baseUrl http://localhost:3000
      - run:
          name: Close Sauce Tunnel
          command: |
            pkill sc
            sleep 5 # shutting down the tunnel usually takes a few second, lets let it clean up gracefully

  deploy:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: hlx deploy
          command: npm run deploy
      - run:
          name: Persist post-deploy helix-config
          command: |
            set -exu
            mkdir -p /tmp/workspace
            cp helix-config.yaml /tmp/workspace/.
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - helix-config.yaml

  post_deploy_tests:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: Run post-deploy tests
          command: npm run test:post-deploy

  commit_deploy_tag:
    executor: helix
    steps:
      - setup_fs
      - run:
          name: Commit helix config to master
          command: |
            git config user.name "dxbot"
            git config user.email "dxbot@adobe.com"
            git stash
            git checkout master
            git pull origin --tags master
            git stash pop
            git commit -am "🐣 enshrining config post-deploy [ci skip]" 
            git push origin master

workflows:
  version: 2.1
  continously_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build
      - unit_tests:
          requires:
            - build
      - end_to_end_tests:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - unit_tests
            - end_to_end_tests
          filters:
            branches:
              only: master
      - post_deploy_tests:
          requires:
            - deploy
          filters:
            branches:
              only: master
      - commit_deploy_tag:
          requires:
            - post_deploy_tests
          filters:
            branches:
              only: master
